export const arr = {
  ujian: [
    {
      juz: "",
      hafalan: "",
      tajwid: "",
      total: "",
      keterangan: "",
    },
    {
      juz: "",
      hafalan: "",
      tajwid: "",
      total: "",
      keterangan: "",
    },
    {
      juz: "",
      hafalan: "",
      tajwid: "",
      total: "",
      keterangan: "",
    },
    {
      juz: "",
      hafalan: "",
      tajwid: "",
      total: "",
      keterangan: "",
    },
    {
      juz: "",
      hafalan: "",
      tajwid: "",
      total: "",
      keterangan: "",
    },
    {
      juz: "",
      hafalan: "",
      tajwid: "",
      total: "",
      keterangan: "",
    },
    {
      juz: "",
      hafalan: "",
      tajwid: "",
      total: "",
      keterangan: "",
    },
    {
      juz: "",
      hafalan: "",
      tajwid: "",
      total: "",
      keterangan: "",
    },
    {
      juz: "",
      hafalan: "",
      tajwid: "",
      total: "",
      keterangan: "",
    },
    {
      juz: "",
      hafalan: "",
      tajwid: "",
      total: "",
      keterangan: "",
    },
  ],
};
